version: "3"
services:
  area_web:
    image: node:lts
    # env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app/area_web
    command: sh -c "cd /app/area_web && npm install && npm start clear"
